version: '3.8'

services:
  myds:
    build: ./app
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    # env_file:
    #   - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - myds

volumes:
  postgres_data:
  static_volume:
  media_volume: