# Generated by Django 4.0.4 on 2022-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstations',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
