# Generated by Django 4.0.4 on 2022-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_workstations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstations',
            name='slug',
            field=models.SlugField(blank=True, max_length=9, unique=True),
        ),
    ]
