# Generated by Django 4.0.4 on 2022-05-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_workstations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstations',
            name='installed',
            field=models.TextField(blank=True, verbose_name='apps installed'),
        ),
        migrations.AlterField(
            model_name='workstations',
            name='os_build',
            field=models.CharField(blank=True, max_length=100, verbose_name='operating system'),
        ),
    ]
