# Generated by Django 4.0.4 on 2022-05-11 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_workstations_installed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstations',
            name='id',
        ),
        migrations.AlterField(
            model_name='workstations',
            name='muid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
