# Generated by Django 4.0.4 on 2022-05-12 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_workstations_id_alter_workstations_muid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('muid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('w_name', models.CharField(blank=True, max_length=9, verbose_name='workstation name')),
                ('slug', models.SlugField(blank=True, max_length=9, unique=True)),
                ('belarc_file', models.FileField(blank=True, upload_to='belarc_files/')),
                ('anti_virus', models.CharField(blank=True, max_length=100, verbose_name='anti-virus')),
                ('installed', models.TextField(blank=True, verbose_name='apps installed')),
                ('os_build', models.CharField(blank=True, max_length=100, verbose_name='network speed')),
                ('is_installed', models.BooleanField(default=False, verbose_name='is adobe reader installed')),
            ],
        ),
        migrations.DeleteModel(
            name='Workstations',
        ),
    ]
