# Generated by Django 4.0.4 on 2022-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_workstation_delete_workstations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='network_speed',
            field=models.CharField(blank=True, max_length=100, verbose_name='network speed'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='os_build',
            field=models.CharField(blank=True, max_length=100, verbose_name='operating system'),
        ),
    ]
